//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class websiteEntities : DbContext
    {
        public websiteEntities()
            : base("name=websiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<ctDaodien> ctDaodien { get; set; }
        public virtual DbSet<ctDienvien> ctDienvien { get; set; }
        public virtual DbSet<ctlogin> ctlogin { get; set; }
        public virtual DbSet<ctTheloai> ctTheloai { get; set; }
        public virtual DbSet<daodien> daodien { get; set; }
        public virtual DbSet<Dienvien> Dienvien { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<phim> phim { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tapphim> tapphim { get; set; }
        public virtual DbSet<tintuc_phim> tintuc_phim { get; set; }
        public virtual DbSet<theloai_phim> theloai_phim { get; set; }
    }
}
