//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim
{
    using System;
    using System.Collections.Generic;
    
    public partial class tapphim
    {
        public int id_tapphim { get; set; }
        public Nullable<int> id_phim { get; set; }
        public Nullable<int> tapso { get; set; }
        public Nullable<System.DateTime> ngay_update { get; set; }
        public string link { get; set; }
    
        public virtual phim phim { get; set; }
    }
}
