//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim
{
    using System;
    using System.Collections.Generic;
    
    public partial class tintuc_phim
    {
        public int id_tintuc_phim { get; set; }
        public string tieu_de { get; set; }
        public string anh_daidien { get; set; }
        public string tom_tat_tin { get; set; }
        public string noidung { get; set; }
    }
}
